
export const PerspectiveArticleProps = [
    {
        title:"Industry4.0",
        href:"/Contents/SERVICE/ServiceContents/Industry/Industry4.0/",
        description:"ドイツ政府が「Industry 4.0」を進める背景は？「Industry 4.0」の主要コンセプトは？"
    },
    {
        title:"【考察】インダストリー4.0",
        href:"",
        description:"インダストリー4.0（Industry4.0）およびインダストリアル・インターネット（Industrial Internet）への考察"
    },
    {
        title:"IoTで何を目指しますか？",
        href:"",
        description:"Industry4.0、IoTといった潮流の中で各企業は何を目指すべきでしょうか？"
    },
    {
        title:"工作機械のためのオープンプロトコル“MTConnect”",
        href:"",
        description:"工作機械の稼働データ取得の標準プロトコル：MTConnectのご紹介"
    },
    {
        title:"MES領域のKPI国際標準“ISO22400”",
        href:"",
        description:"ISO22400の概要、経緯、他の規格との関連についての紹介"
    },
    {
        title:"製造業のDX(デジタルトランスフォーメーション)",
        href:"",
        description:"製造業のDX(デジタルトランスフォーメーション)の効果とは"
    },
    {
        title:"自動車業界のDX(デジタルトランスフォーメーション)",
        href:"",
        description:"自動車業界のDX(デジタルトランスフォーメーション)の効果とは"
    },
    {
        title:"DX導入事例集",
        href:"",
        description:"弊社でサポートさせて頂いたDX化の事例集を送付致します"
    },
    {
        title:"機械製造業におけるIT化推進・DX(デジタルトランスフォーメーション)",
        href:"",
        description:"人とロボット、新しい機械と古い機械が混在する機械製造業におけるIT化・DX推進は、非常に悩ましいテーマです"
    },
    {
        title:"デジタルツインの活用",
        href:"",
        description:"3D解析技術、デジタルツインの活用案の紹介"
    },
    {
        title:"工場でのIoT　事例から学ぶ効果と課題",
        href:"",
        description:"工場でのIoT化で期待される効果と実際を、事例に基づいて解説"
    }
]


export const SolutionServiceProps = [
    {
        title:"スマートファクトリー",
        href:"",
        description:"スマートな工場の実現に向けて"
    },
    {
        title:"スマートファクトリークラウド",
        href:"",
        description:"製造現場に低コスト短期間でIoTを導入するためのスマートファクトリークラウドの紹介"
    },
    {
        title:"品質管理とスマートファクトリー",
        href:"",
        description:"スマートファクトリーでの品質管理の実現"
    },
    {
        title:"Industry 4.0に対応したい",
        href:"",
        descriptoin:"IoTやCPS、更にIoSといったものを活用した、新しい工場・製造業への転換をご支援いたします。"
    },
    {
        title:"スマートファクトリー実現に必要な人材",
        href:"",
        description:"スマートファクトリーシステム構築のために必要な人材"
    },
    {
        title:"AIスクエア",
        href:"",
        description:"AIでヒトに依存しないモノづくりをサポート"
    },
    {
        title:"製造業におけるIoT",
        href:"",
        description:"製造業におけるIoTには、２つのタイプがあります。１つは、自社製品をIoT化し稼働時のデータを収集・解析することで、もう１つは、自社の製造現場の設備・機器などをIoT化し、生産性改善や品質向上を狙うものです。"
    },
    {
        title:"効率的にトレーサビリティを向上させたい",
        href:"",
        description:"各種設備から直接データを収集し、手間を掛けずに記録を残します。"
    },
    {
        title:"統計的品質管理を、効率よく実施したい",
        href:"",
        description:<>データ取得から異常傾向の発見までを自動化し、"管理すべきポイント"を明示します。</>
    },
    {
        title:"製造現場のビッグデータ活用",
        href:"",
        description:"製造現場の設備・機器など生産に関わるモノをIoT化することで、大量のデータを収集・蓄積し、これを活用することにより、従来は難しかった生産性向上や品質向上／安定に寄与するヒントの抽出が可能です。"
    },
    {
        title:"IoTで成形工程を改善する",
        href:"",
        description:"成形工程でのスマートファクトリー実現のポイントをご紹介します。"
    },
    {
        title:"IoTで加工工程を改善する",
        href:"",
        description:"加工工程にスマートファクトリーを導入する際のイメージと、収集したデータの活用例についてご紹介します。"
    },
    {
        title:"スマートファクトリー、IoT活用における弊社の強み",
        href:"",
        description:"エイムネクストには、様々な専門家がいます"
    },
    {
        title:"ST言語による構造化プログラミング研修",
        href:"",
        description:"本コースではST言語の習得に加えて、プログラミングの基礎となる設計手法、コードの記述方法、テスト手法の解説も行います。"
    },
    {
        title:"スマートファクトリー研修",
        href:"",
        description:"スマートファクトリー第一人者による、IoT/AI活用の最新情報も学習できる研修コースです。スマートファクトリーをどのように捉え、どのように生かしていけばよいか、実例とデモを用いて解説します。"
    },
    {
        title:"滞留・リードタイム・ボトルネック見える化ツール",
        href:"",
        description:"簡単に始められる、工場で実際に起きている滞留とリードタイム・ボトルネックを見える化するツールをご提供します。"
    },
    {
        title:"工場発のROE改善ゲーム",
        href:"",
        description:"製造現場での日々の活動とROEがどの様に繋がっているのかをお伝えする為のゲームをご提供します。"
    },
    {
        title:"不具合発生状況の可視化と原因追及プログラム",
        href:"",
        description:"データに基づく不具合対策を今度こそ実現しませんか。"
    }
]